name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.27.1' # Replace with the latest stable version

    - name: Debug Flutter Installation
      run: flutter doctor -v

    - name: Switch to Stable Channel
      run: flutter channel stable

    - name: Install dependencies
      run: flutter pub get

    - name: Build Flutter Web
      run: flutter build web --release

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build/web

    - name: Check if GitHub Pages is Available
      run: |
        # Replace <USERNAME> and <REPOSITORY> with your GitHub username and repository name
        PAGE_URL="https://wajdi2001.github.io/piece_autos/"
        
        echo "Checking if GitHub Pages is available at $PAGE_URL..."
        
        for i in {1..10}; do
          STATUS=$(curl -o /dev/null -s -w "%{http_code}" $PAGE_URL)
          if [ "$STATUS" -eq 200 ]; then
            echo "GitHub Pages is live at $PAGE_URL"
            exit 0
          else
            echo "GitHub Pages is not yet available. Retrying in 30 seconds... ($i/10)"
            sleep 30
          fi
        done
        
        echo "GitHub Pages did not become available. Please check your deployment."
        exit 1
